CREATE USER UNIFIED_LOG IDENTIFIED BY Password1;

GRANT CREATE PROCEDURE, CREATE SESSION, CREATE TABLE,CREATE TRIGGER, CREATE TYPE, CREATE VIEW, "CONNECT", "RESOURCE" TO UNIFIED_LOG;

CREATE USER UNIFIED_USE IDENTIFIED BY Password1;

GRANT CREATE PROCEDURE, CREATE SESSION, CREATE TABLE,CREATE TRIGGER, CREATE TYPE, CREATE VIEW, "CONNECT", "RESOURCE" TO UNIFIED_USE;

