SET DEFINE OFF;

ALTER SESSION SET CURRENT_SCHEMA = UNIFIED_USE;

--DROP TABLE UAM_ASSET CASCADE CONSTRAINTS ;
--
--DROP TABLE UAM_LOCAL CASCADE CONSTRAINTS ;
--
--DROP TABLE UAM_ROLE CASCADE CONSTRAINTS ;
--
--DROP TABLE UAM_ROLE_ASSETS CASCADE CONSTRAINTS ;
--
--DROP TABLE UAM_SESSION CASCADE CONSTRAINTS ;
--
--DROP TABLE UAM_SHELL CASCADE CONSTRAINTS ;
--
--DROP TABLE UAM_USER CASCADE CONSTRAINTS ;
--
--DROP TABLE UAM_USER_ROLE CASCADE CONSTRAINTS ;
--
--DROP TABLE UAM_USER_SETTINGS CASCADE CONSTRAINTS ;


CREATE TABLE UAM_ASSET
  (
    ID               NUMBER NOT NULL ,
    TYPE             VARCHAR2 (128 CHAR) NOT NULL ,
    NAME             VARCHAR2 (128 CHAR) NOT NULL ,
    DESCRIPTION      VARCHAR2 (128 CHAR) ,
    ACTIVE           CHAR (1 BYTE) NOT NULL ,
    CREATION_USER    VARCHAR2 (64 CHAR) NOT NULL ,
    CREATION_DATE    DATE NOT NULL ,
    LAST_UPDATE_USER VARCHAR2 (64 CHAR) NOT NULL ,
    LAST_UPDATE_DATE DATE NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UAM_ASSET_PK ON UAM_ASSET
  (
    ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_ASSET ADD CONSTRAINT UAM_ASSET_PK PRIMARY KEY ( ID ) ;

CREATE TABLE UAM_LOCAL
  (
    ID               NUMBER NOT NULL ,
    NAME             VARCHAR2 (128 CHAR) NOT NULL ,
    EXTERNAL_KEY     VARCHAR2 (128 CHAR) NOT NULL ,
    GATEWAY          VARCHAR2 (20 CHAR) NOT NULL ,
    START_ADDRESS    NUMBER NOT NULL ,
    END_ADDRESS      NUMBER NOT NULL ,
    EMAIL            VARCHAR2 (128 CHAR) ,
    CREATION_USER    VARCHAR2 (64 CHAR) NOT NULL ,
    CREATION_DATE    DATE NOT NULL ,
    LAST_UPDATE_USER VARCHAR2 (64 CHAR) NOT NULL ,
    LAST_UPDATE_DATE DATE NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UAM_LOCAL_PK ON UAM_LOCAL
  (
    ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_LOCAL ADD CONSTRAINT UAM_LOCAL_PK PRIMARY KEY ( ID ) ;

CREATE TABLE UAM_ROLE
  (
    ID               NUMBER NOT NULL ,
    TYPE             VARCHAR2 (128 CHAR) ,
    NAME             VARCHAR2 (128 CHAR) NOT NULL ,
    DESCRIPTION      VARCHAR2 (128 CHAR) ,
    ACTIVE           CHAR (1 BYTE) NOT NULL ,
    CREATION_USER    VARCHAR2 (64 CHAR) NOT NULL ,
    CREATION_DATE    DATE NOT NULL ,
    LAST_UPDATE_USER VARCHAR2 (64 CHAR) NOT NULL ,
    LAST_UPDATE_DATE DATE NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UAM_ROLE_PK ON UAM_ROLE
  (
    ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_ROLE ADD CONSTRAINT UAM_ROLE_PK PRIMARY KEY ( ID ) ;

CREATE TABLE UAM_ROLE_ASSETS
  (
    ROLE_ID           NUMBER NOT NULL ,
    ASSET_ID          NUMBER NOT NULL ,
    USER_EXPRESSION   VARCHAR2 (256 CHAR) ,
    TARGET_EXPRESSION VARCHAR2 (256 CHAR) ,
    ACTIVE            CHAR (1 BYTE) ,
    CREATION_USER     VARCHAR2 (64 CHAR) NOT NULL ,
    CREATION_DATE     DATE NOT NULL ,
    LAST_UPDATE_USER  VARCHAR2 (64 CHAR) NOT NULL ,
    LAST_UPDATE_DATE  DATE NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UAM_ROLE_ASSETS__IDX ON UAM_ROLE_ASSETS
  (
    ROLE_ID ASC , ASSET_ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_ROLE_ASSETS ADD CONSTRAINT UAM_ROLE_ASSETS__IDX PRIMARY KEY ( ROLE_ID, ASSET_ID ) ;

CREATE TABLE UAM_SESSION
  (
    ID               NUMBER NOT NULL ,
    TOKEN            VARCHAR2 (40 CHAR) NOT NULL ,
    IP               VARCHAR2 (32 CHAR) ,
    HOSTNAME         VARCHAR2 (64 CHAR) ,
    LOCAL_ID         NUMBER ,
    ROLE_ID          NUMBER ,
    USER_ID          NUMBER NOT NULL ,
    CREATION_USER    VARCHAR2 (64 CHAR) NOT NULL ,
    CREATION_DATE    DATE NOT NULL ,
    LAST_UPDATE_USER VARCHAR2 (64 CHAR) NOT NULL ,
    LAST_UPDATE_DATE DATE NOT NULL ,
    CUSTOM_PROPERTIES CLOB ,
    SHELL_ID NUMBER
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOB
  (
    CUSTOM_PROPERTIES
  )
  STORE AS
  (
    TABLESPACE SYSTEM STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT ) CHUNK 8192 RETENTION ENABLE STORAGE IN ROW NOCACHE LOGGING
  ) ;
CREATE UNIQUE INDEX UAM_SESSION_PK ON UAM_SESSION
  (
    ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_SESSION ADD CONSTRAINT UAM_SESSION_PK PRIMARY KEY ( ID ) ;

CREATE TABLE UAM_SHELL
  (
    ID                   NUMBER NOT NULL ,
    NAME                 VARCHAR2 (128 CHAR) NOT NULL ,
    DESCRIPTION          VARCHAR2 (128 CHAR) ,
    URL                  VARCHAR2 (128 CHAR) NOT NULL ,
    IS_DEFAULT           CHAR (1 BYTE) NOT NULL ,
    REQUIRES_LOCAL       CHAR (1 BYTE) NOT NULL ,
    REQUIRES_SINGLE_ROLE CHAR (1 BYTE) ,
    DEFAULT_LOCAL        NUMBER ,
    CREATION_USER        VARCHAR2 (64 CHAR) NOT NULL ,
    CREATION_DATE        DATE NOT NULL ,
    LAST_UPDATE_USER     VARCHAR2 (64 CHAR) NOT NULL ,
    LAST_UPDATE_DATE     DATE NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UAM_SHELL_PK ON UAM_SHELL
  (
    ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_SHELL ADD CONSTRAINT UAM_SHELL_PK PRIMARY KEY ( ID ) ;

CREATE TABLE UAM_USER
  (
    ID                      NUMBER NOT NULL ,
    USERNAME                VARCHAR2 (100 CHAR) NOT NULL ,
    NAME                    VARCHAR2 (128 CHAR) NOT NULL ,
    PASSWORD                VARCHAR2 (64 CHAR) ,
    STATUS                  NUMBER (1) DEFAULT 0 NOT NULL ,
    LAST_STATUS_CHANGE_DATE DATE NOT NULL ,
    LAST_LOGIN_DATE         DATE ,
    LAST_LOCAL_ID           NUMBER ,
    CREATION_USER           VARCHAR2 (64 CHAR) NOT NULL ,
    CREATION_DATE           DATE NOT NULL ,
    LAST_UPDATE_USER        VARCHAR2 (64 CHAR) NOT NULL ,
    LAST_UPDATE_DATE        DATE NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UAM_USER_PK ON UAM_USER
  (
    ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_USER ADD CONSTRAINT UAM_USER_PK PRIMARY KEY ( ID ) ;

CREATE TABLE UAM_USER_ROLE
  (
    ID         NUMBER NOT NULL ,
    ROLE_ID    NUMBER NOT NULL ,
    USER_ID    NUMBER NOT NULL ,
    SHELL_ID   NUMBER NOT NULL ,
    IS_DEFAULT CHAR (1 BYTE)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX USER_ROLE_SHELL_IDX ON UAM_USER_ROLE
  (
    ROLE_ID ASC , USER_ID ASC , SHELL_ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_USER_ROLE ADD CONSTRAINT UAM_USER_PROFILE__IDX PRIMARY KEY ( ID ) ;

CREATE TABLE UAM_USER_SETTINGS
  (
    USER_ID          NUMBER NOT NULL ,
    LOCALE           VARCHAR2 (32 CHAR) ,
    DATE_FORMAT      VARCHAR2 (32 CHAR) ,
    TIME_FORMAT      VARCHAR2 (32 CHAR) ,
    NUMBERIC_FORMAT  VARCHAR2 (32 CHAR) ,
    CREATION_USER    VARCHAR2 (64 CHAR) NOT NULL ,
    CREATION_DATE    DATE NOT NULL ,
    LAST_UPDATE_USER VARCHAR2 (64 CHAR) NOT NULL ,
    LAST_UPDATE_DATE DATE NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UFE_USE LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UAM_USER_SETTINGS_PK ON UAM_USER_SETTINGS
  (
    USER_ID ASC
  )
  TABLESPACE SYSTEM PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE UAM_USER_SETTINGS ADD CONSTRAINT UAM_USER_SETTINGS_PK PRIMARY KEY ( USER_ID ) ;

ALTER TABLE UAM_ROLE_ASSETS ADD CONSTRAINT FK_ASS_10 FOREIGN KEY ( ROLE_ID ) REFERENCES UAM_ROLE ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_ROLE_ASSETS ADD CONSTRAINT FK_ASS_11 FOREIGN KEY ( ASSET_ID ) REFERENCES UAM_ASSET ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_USER_ROLE ADD CONSTRAINT FK_ASS_13 FOREIGN KEY ( USER_ID ) REFERENCES UAM_USER ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_SESSION ADD CONSTRAINT UAM_SESSION_UAM_LOCAL_FK FOREIGN KEY ( LOCAL_ID ) REFERENCES UAM_LOCAL ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_SESSION ADD CONSTRAINT UAM_SESSION_UAM_ROLE_FK FOREIGN KEY ( ROLE_ID ) REFERENCES UAM_ROLE ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_SESSION ADD CONSTRAINT UAM_SESSION_UAM_USER_FK FOREIGN KEY ( USER_ID ) REFERENCES UAM_USER ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_SESSION ADD CONSTRAINT UAM_SHELL_FK FOREIGN KEY ( SHELL_ID ) REFERENCES UAM_SHELL ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_SHELL ADD CONSTRAINT UAM_SHELL_UAM_LOCAL_FK FOREIGN KEY ( DEFAULT_LOCAL ) REFERENCES UAM_LOCAL ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_USER_ROLE ADD CONSTRAINT UAM_USER_ROLE_UAM_ROLE_FK FOREIGN KEY ( ROLE_ID ) REFERENCES UAM_ROLE ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_USER_ROLE ADD CONSTRAINT UAM_USER_ROLE_UAM_SHELL_FK FOREIGN KEY ( SHELL_ID ) REFERENCES UAM_SHELL ( ID ) NOT DEFERRABLE ;

ALTER TABLE UAM_USER_SETTINGS ADD CONSTRAINT UAM_USER_SETTINGS_UAM_USER_FK FOREIGN KEY ( USER_ID ) REFERENCES UAM_USER ( ID ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE UAM_USER ADD CONSTRAINT UAM_USER_UAM_LOCAL_FK FOREIGN KEY ( LAST_LOCAL_ID ) REFERENCES UAM_LOCAL ( ID ) NOT DEFERRABLE ;

