ALTER SESSION SET CURRENT_SCHEMA = UNIFIED_USE;

--------------------------------------------------------
--  DDL for Sequence ORCHESTRATOR_SEQ
--------------------------------------------------------
CREATE SEQUENCE "ORCHESTRATOR_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence ORCH_KEYWORD_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "ORCH_KEYWORD_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence REF_DATA_ITEM_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "REF_DATA_ITEM_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence ROUTE_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "ROUTE_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Table ORCHESTRATOR
  --------------------------------------------------------
  CREATE TABLE "ORCHESTRATOR"
    (
      "ID" NUMBER(10,0),
      "SCRIPT" CLOB,
      "STATUS" CLOB,
      "OVERALL_STATUS"       VARCHAR2(50 BYTE),
      "DATA_HASH"            NUMBER(16,0),
      "CREATION_DATE"        DATE,
      "MODIFIED_DATE"        DATE,
      "CREATION_USER"        VARCHAR2(50 BYTE),
      "LAST_UPDATE_USER"     VARCHAR2(255 BYTE),
      "LAST_PROCESS"         VARCHAR2(255 BYTE),
      "LAST_SESSION_ID"      VARCHAR2(255 BYTE),
      "LAST_LOCATION"        VARCHAR2(255 BYTE),
      "LAST_CONVERSATION_ID" VARCHAR2(255 BYTE),
      "LAST_HOSTNAME"        VARCHAR2(255 BYTE),
      "LAST_CLIENT_IP"       VARCHAR2(255 BYTE),
      "LAST_PROFILE"         VARCHAR2(255 BYTE),
      "LAST_CHANNEL"         VARCHAR2(16 CHAR)
    )
    TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Table ORCH_KEYWORD
  --------------------------------------------------------
  CREATE TABLE "ORCH_KEYWORD"
    (
      "ID"        NUMBER(10,0),
      "NAME"      VARCHAR2(50 BYTE),
      "KEY_VALUE" VARCHAR2(100 BYTE),
      "ORCH_ID"   NUMBER(10,0)
    )
    TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Table REFDATAITEM
  --------------------------------------------------------
  CREATE TABLE "REFDATAITEM"
    (
      "REFDATAITEM_ID" NUMBER,
      "EXPORTABLE"     NUMBER(1,0),
      "NAME"           VARCHAR2(255 BYTE),
      "TIME"           DATE,
      "TYPE"           VARCHAR2(255 BYTE),
      "VALUE" CLOB,
      "VERSION" NUMBER
    )
    TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Table ROUTE
  --------------------------------------------------------
  CREATE TABLE "ROUTE"
    (
      "ID"                   NUMBER(15,0),
      "NAME"                 VARCHAR2(255 CHAR),
      "MATCHING_SCRIPT"      VARCHAR2(4000 CHAR),
      "ACTION_CONFIGURATION" VARCHAR2(4000 CHAR),
      "CREATION_DATE"        TIMESTAMP (6),
      "CREATION_USER"        VARCHAR2(32 CHAR),
      "LAST_UPDATE_DATE"     TIMESTAMP (6),
      "LAST_UPDATE_USER"     VARCHAR2(32 CHAR),
      "ORCH_EVAL" CLOB,
      "IS_PUBLIC" NUMBER(1,0) DEFAULT 0
    ) TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Table SEQUENCE_TABLE
  --------------------------------------------------------
  CREATE TABLE "SEQUENCE_TABLE"
    (
      "SEQUENCE_NAME" VARCHAR2(255 BYTE),
      "NEXT_VAL"      NUMBER
    )
    SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Index ORCHESTRATOR_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "ORCHESTRATOR_PK" ON "ORCHESTRATOR"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Index ORCH_KEYWORD_FK01
  --------------------------------------------------------
  CREATE INDEX "ORCH_KEYWORD_FK01" ON "ORCH_KEYWORD"
    (
      "ORCH_ID"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Index ORCH_KEYWORD_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "ORCH_KEYWORD_PK" ON "ORCH_KEYWORD"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Index REFDATAITEM_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "REFDATAITEM_PK" ON "REFDATAITEM"
  (
    "REFDATAITEM_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Index ROUTE_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "ROUTE_PK" ON "ROUTE"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Index ROUTE_U01
  --------------------------------------------------------
CREATE UNIQUE INDEX "ROUTE_U01" ON "ROUTE"
  (
    "NAME"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  DDL for Index SEQUENCE_TABLE_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "SEQUENCE_TABLE_PK" ON "SEQUENCE_TABLE"
  (
    "SEQUENCE_NAME"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_USE";
  --------------------------------------------------------
  --  Constraints for Table ORCHESTRATOR
  --------------------------------------------------------
  ALTER TABLE "ORCHESTRATOR" ADD CONSTRAINT "ORCHESTRATOR_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_USE" ENABLE;
  ALTER TABLE "ORCHESTRATOR" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
  ALTER TABLE "ORCHESTRATOR" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "ORCHESTRATOR" MODIFY ("DATA_HASH" NOT NULL ENABLE);
  ALTER TABLE "ORCHESTRATOR" MODIFY ("OVERALL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ORCHESTRATOR" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ORCHESTRATOR" MODIFY ("SCRIPT" NOT NULL ENABLE);
  ALTER TABLE "ORCHESTRATOR" MODIFY ("ID" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Constraints for Table ORCH_KEYWORD
  --------------------------------------------------------
  ALTER TABLE "ORCH_KEYWORD" ADD CONSTRAINT "ORCH_KEYWORD_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_USE" ENABLE;
  ALTER TABLE "ORCH_KEYWORD" MODIFY ("ORCH_ID" NOT NULL ENABLE);
  ALTER TABLE "ORCH_KEYWORD" MODIFY ("KEY_VALUE" NOT NULL ENABLE);
  ALTER TABLE "ORCH_KEYWORD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ORCH_KEYWORD" MODIFY ("ID" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Constraints for Table REFDATAITEM
  --------------------------------------------------------
  ALTER TABLE "REFDATAITEM" ADD CONSTRAINT "REFDATAITEM_PK" PRIMARY KEY ("REFDATAITEM_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_USE" ENABLE;
  ALTER TABLE "REFDATAITEM" ADD CHECK (EXPORTABLE IN (1,0)) ENABLE;
  ALTER TABLE "REFDATAITEM" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "REFDATAITEM" MODIFY ("EXPORTABLE" NOT NULL ENABLE);
  ALTER TABLE "REFDATAITEM" MODIFY ("REFDATAITEM_ID" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Constraints for Table ROUTE
  --------------------------------------------------------
  ALTER TABLE "ROUTE" ADD CONSTRAINT "ROUTE_U01" UNIQUE ("NAME") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_USE" ENABLE;
  ALTER TABLE "ROUTE" MODIFY ("IS_PUBLIC" NOT NULL ENABLE);
  ALTER TABLE "ROUTE" MODIFY ("LAST_UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "ROUTE" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ROUTE" MODIFY ("CREATION_USER" NOT NULL ENABLE);
  ALTER TABLE "ROUTE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "ROUTE" MODIFY ("ACTION_CONFIGURATION" NOT NULL ENABLE);
  ALTER TABLE "ROUTE" MODIFY ("MATCHING_SCRIPT" NOT NULL ENABLE);
  ALTER TABLE "ROUTE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ROUTE" MODIFY ("ID" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Ref Constraints for Table ORCH_KEYWORD
  --------------------------------------------------------
  ALTER TABLE "ORCH_KEYWORD" ADD CONSTRAINT "ORCH_KEYWORD_FK01" FOREIGN KEY ("ORCH_ID") REFERENCES "ORCHESTRATOR" ("ID") ENABLE;
