ALTER SESSION SET CURRENT_SCHEMA = UNIFIED_LOG;
--------------------------------------------------------
--  DDL for Sequence CFG_CRITERIA_SEQ
--------------------------------------------------------
CREATE SEQUENCE "CFG_CRITERIA_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence CFG_CUSTOM_EVENT_TYPE_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "CFG_CUSTOM_EVENT_TYPE_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 261 CACHE 20 NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence CFG_EVENTS_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "CFG_EVENTS_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence CFG_LOCAL_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "CFG_LOCAL_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 585 CACHE 20 NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence CFG_PROCESSES_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "CFG_PROCESSES_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 785 CACHE 20 NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence CFG_PROFILES_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "CFG_PROFILES_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 565 CACHE 20 NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence CFG_SOAPSERVICES_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "CFG_SOAPSERVICES_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 400 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence CFG_USERS_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "CFG_USERS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1285 CACHE 20 NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence LG_ENTRY_PARAMETERS_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "LG_ENTRY_PARAMETERS_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22662 NOCACHE NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Sequence LG_LOGENTRIES_SEQ
  --------------------------------------------------------
CREATE SEQUENCE "LG_LOGENTRIES_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1399267 CACHE 20 NOORDER NOCYCLE ;
  --------------------------------------------------------
  --  DDL for Table CFG_CRITERIA
  --------------------------------------------------------
  CREATE TABLE "CFG_CRITERIA"
    (
      "ID"            NUMBER(15,0),
      "NAME"          VARCHAR2(64 BYTE),
      "TYPE"          VARCHAR2(10 BYTE),
      "REGEX"         VARCHAR2(128 BYTE),
      "MASK_TYPE"     VARCHAR2(10 BYTE),
      "MASK"          VARCHAR2(10 BYTE),
      "STATUS_MATCH"  VARCHAR2(128 BYTE),
      "STATUS_OUTPUT" NUMBER
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_CUSTOM_EVENT_TYPE
  --------------------------------------------------------
  CREATE TABLE "CFG_CUSTOM_EVENT_TYPE"
    (
      "ID"   NUMBER(15,0),
      "NAME" VARCHAR2(128 CHAR)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_EVENT_CRITERIA
  --------------------------------------------------------
  CREATE TABLE "CFG_EVENT_CRITERIA"
    (
      "EVENT_ID"    NUMBER(15,0),
      "CRITERIA_ID" NUMBER(15,0)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_EVENTS
  --------------------------------------------------------
  CREATE TABLE "CFG_EVENTS"
    (
      "ID"           NUMBER(15,0),
      "EVENT_NAME"   VARCHAR2(256 BYTE),
      "LOG_EVENT"    NUMBER(1,0) DEFAULT 1,
      "LOG_JSON_IN"  NUMBER(1,0) DEFAULT 1,
      "LOG_JSON_OUT" NUMBER(1,0) DEFAULT 1
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_LOCAL
  --------------------------------------------------------
  CREATE TABLE "CFG_LOCAL"
    (
      "ID"   NUMBER(10,0),
      "NAME" VARCHAR2(50 CHAR)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_LOGCRITERIA
  --------------------------------------------------------
  CREATE TABLE "CFG_LOGCRITERIA"
    (
      "LABEL"      VARCHAR2(50 CHAR),
      "ID"         NUMBER,
      "EVALSOAPIN" CHAR(1 BYTE),
      "CRITERION"  VARCHAR2(50 CHAR)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_MASKCRITERIA
  --------------------------------------------------------
  CREATE TABLE "CFG_MASKCRITERIA"
    (
      "SERVICEID"  NUMBER(*,0),
      "EVALSOAPIN" CHAR(1 BYTE),
      "CRITERION"  VARCHAR2(50 CHAR),
      "MASK"       VARCHAR2(50 CHAR),
      "ID"         NUMBER
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_PROCESSES
  --------------------------------------------------------
  CREATE TABLE "CFG_PROCESSES"
    (
      "ID"          NUMBER(10,0),
      "DESCRIPTION" VARCHAR2(100 CHAR)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_PROFILES
  --------------------------------------------------------
  CREATE TABLE "CFG_PROFILES"
    (
      "ID"          NUMBER(10,0),
      "NAME"        VARCHAR2(25 CHAR),
      "DESCRIPTION" VARCHAR2(100 CHAR)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_SERVICESCRITERIA
  --------------------------------------------------------
  CREATE TABLE "CFG_SERVICESCRITERIA"
    (
      "SERVICEID"  NUMBER(10,0),
      "CRITERIAID" NUMBER
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_SOAP_CRITERIA
  --------------------------------------------------------
  CREATE TABLE "CFG_SOAP_CRITERIA"
    (
      "SOAP_ID"     NUMBER(15,0),
      "CRITERIA_ID" NUMBER(15,0)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_SOAPSERVICES
  --------------------------------------------------------
  CREATE TABLE "CFG_SOAPSERVICES"
    (
      "SERVICEID"      NUMBER(10,0),
      "SERVICENAME"    VARCHAR2(255 CHAR),
      "LOG_SERVICE"    NUMBER(1,0),
      "STORE_SOAP_IN"  NUMBER(1,0),
      "STORE_SOAP_OUT" NUMBER(1,0),
      "SERVICEKEY"     VARCHAR2(255 BYTE)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_SUCCESSCRITERIA
  --------------------------------------------------------
  CREATE TABLE "CFG_SUCCESSCRITERIA"
    (
      "LABEL"      VARCHAR2(50 CHAR),
      "EVALSOAPIN" CHAR(1 BYTE),
      "CRITERION"  VARCHAR2(50 CHAR),
      "SERVICEID"  NUMBER
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table CFG_USERS
  --------------------------------------------------------
  CREATE TABLE "CFG_USERS"
    (
      "ID"   NUMBER(10,0),
      "NAME" VARCHAR2(50 CHAR)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table LG_CUSTOM
  --------------------------------------------------------
  CREATE TABLE "LG_CUSTOM"
    (
      "LOGENTRYID" NUMBER(10,0),
      "EVENT_TYPE" NUMBER(10,0)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table LG_ENTRY_PARAMETERS
  --------------------------------------------------------
  CREATE TABLE "LG_ENTRY_PARAMETERS"
    (
      "ID"           NUMBER(15,0),
      "LOG_ENTRY_ID" NUMBER(10,0),
      "CRITERIA_ID"  NUMBER(15,0),
      "VALUE"        VARCHAR2(128 BYTE),
      "NAME"         VARCHAR2(32 BYTE)
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Table LG_ERRORSLOG
  --------------------------------------------------------
  CREATE TABLE "LG_ERRORSLOG"
    (
      "LOGENTRYID" NUMBER(10,0),
      "TIMESTAMP"  TIMESTAMP (6),
      "ERRORDETAIL" CLOB,
      "ERRORMESSAGE" VARCHAR2(2000 CHAR)
    )
    TABLESPACE "UFE_LOGVW";
  --------------------------------------------------------
  --  DDL for Table LG_EVENT
  --------------------------------------------------------
  CREATE TABLE "LG_EVENT"
    (
      "LOG_ENTRYID"        NUMBER,
      "EVENT_ID"           NUMBER,
      "EVENT_TYPE"         VARCHAR2(20 CHAR),
      "EVENT_MESSAGE"      VARCHAR2(4000 CHAR),
      "TIMESTAMP"          TIMESTAMP (6),
      "OUTCOME"            NUMBER(1,0),
      "CLASSNAME"          VARCHAR2(255 BYTE),
      "METHODNAME"         VARCHAR2(255 BYTE),
      "TOTALINTERVALTIME"  NUMBER,
      "SERVERINTERVALTIME" NUMBER,
      "JSONIN" CLOB,
      "JSONOUT" CLOB
    )
    TABLESPACE "UFE_LOGVW";
  --------------------------------------------------------
  --  DDL for Table LG_LOGENTRIES
  --------------------------------------------------------
  CREATE TABLE "LG_LOGENTRIES"
    (
      "ID"                NUMBER(10,0),
      "TIMESTAMP"         TIMESTAMP (6),
      "USERID"            NUMBER(10,0),
      "REMOTENAME"        VARCHAR2(256 BYTE),
      "CONTEXTID"         VARCHAR2(50 CHAR),
      "PROCESSID"         NUMBER(10,0),
      "EXTERNALTIMESTAMP" TIMESTAMP (6),
      "SESSIONID"         VARCHAR2(255 CHAR),
      "LOG_TYPE"          NUMBER(1,0),
      "LOCALID"           NUMBER(10,0),
      "PROFILEID"         NUMBER,
      "STATUS"            NUMBER,
      "CONVERSATIONID"    VARCHAR2(50 BYTE),
      "SERVERNAME"        VARCHAR2(255 BYTE),
      "CHANNEL"           VARCHAR2(16 CHAR) DEFAULT 'VFE',
      "MONTH"             NUMBER GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR("EXTERNALTIMESTAMP",'MM'))) VIRTUAL VISIBLE ,
      "DAY"               NUMBER GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR("EXTERNALTIMESTAMP",'DD'))) VIRTUAL VISIBLE
    )
    TABLESPACE "UFE_LOGVW";
  --------------------------------------------------------
  --  DDL for Table LG_SOAPREQUESTS
  --------------------------------------------------------
  CREATE TABLE "LG_SOAPREQUESTS"
    (
      "LOGENTRYID"      NUMBER(10,0),
      "TIMESTAMP"       TIMESTAMP (6),
      "SERVICEID"       NUMBER(10,0),
      "SERVICEHOST"     VARCHAR2(50 CHAR),
      "SERVICEPORT"     NUMBER(10,0),
      "OUTCOME"         VARCHAR2(20 CHAR),
      "MDWINTERVALTIME" NUMBER(20,0),
      "SOAPIN" CLOB,
      "SOAPOUT" CLOB,
      "SUCESSCRITERION"    NUMBER,
      "LOGCRITERIAINFO"    VARCHAR2(50 CHAR),
      "SERVERINTERVALTIME" NUMBER(20,0),
      "TOTALINTERVALTIME"  NUMBER(20,0)
    )
    TABLESPACE "UFE_LOGVW";
  --------------------------------------------------------
  --  DDL for View OPERATION_LOG
  --------------------------------------------------------
CREATE OR REPLACE VIEW "OPERATION_LOG"
  (
    "ID", "SERVICE", "ACCESSID", "FIXEDID", "SIMCARD", "ACCOUNT", "CUSTOMER", "SIGNALMAX", "POS", "USERNAME", "PROCESS", "OPERATION", "TIMESTAMP"
  )
AS
  SELECT LG.ID,
    LGP.SERVICE,
    LGP.ACCESSID,
    LGP.FIXEDID,
    LGP.SIMCARD,
    LGP.ACCOUNT,
    LGP.CUSTOMER,
    LGP.SIGNALMAX,
    LGL.NAME            AS POS,
    CFGUSR.NAME         AS USERNAME,
    CFGPROC.DESCRIPTION AS PROCESS,
    CFGEVT.NAME         AS OPERATION,
    LG.TIMESTAMP
  FROM VFE_LOG.LG_LOGENTRIES LG
  JOIN VFE_LOG.LG_CUSTOM LGC
  ON LG.ID = LGC.LOGENTRYID
  JOIN VFE_LOG.CFG_LOCAL LGL
  ON LG.LOCALID = LGL.ID
  JOIN VFE_LOG.CFG_CUSTOM_EVENT_TYPE CFGEVT
  ON LGC.EVENT_TYPE = CFGEVT.ID
  JOIN VFE_LOG.CFG_USERS CFGUSR
  ON LG.USERID = CFGUSR.ID
  JOIN VFE_LOG.CFG_PROCESSES CFGPROC
  ON LG.PROCESSID = CFGPROC.ID
  LEFT JOIN
    (SELECT LOG_ENTRY_ID,
      SERVICE,
      ACCESSID,
      FIXEDID,
      SIMCARD,
      ACCOUNT,
      CUSTOMER,
      SIGNALMAX
    FROM
      (SELECT DISTINCT LGP.LOG_ENTRY_ID,
        (SELECT LGP_SERVICE.VALUE
        FROM VFE_LOG.LG_ENTRY_PARAMETERS LGP_SERVICE
        WHERE LGP_SERVICE.LOG_ENTRY_ID = LGP.LOG_ENTRY_ID
        AND LGP_SERVICE.NAME           = 'service'
        AND ROWNUM                     < 2
        ) AS SERVICE,
        (SELECT LGP_SERVICE.VALUE
        FROM VFE_LOG.LG_ENTRY_PARAMETERS LGP_SERVICE
        WHERE LGP_SERVICE.LOG_ENTRY_ID = LGP.LOG_ENTRY_ID
        AND LGP_SERVICE.NAME           = 'accessid'
        AND ROWNUM                     < 2
        ) AS ACCESSID,
        (SELECT LGP_SERVICE.VALUE
        FROM VFE_LOG.LG_ENTRY_PARAMETERS LGP_SERVICE
        WHERE LGP_SERVICE.LOG_ENTRY_ID = LGP.LOG_ENTRY_ID
        AND LGP_SERVICE.NAME           = 'fixedid'
        AND ROWNUM                     < 2
        ) AS FIXEDID,
        (SELECT LGP_SERVICE.VALUE
        FROM VFE_LOG.LG_ENTRY_PARAMETERS LGP_SERVICE
        WHERE LGP_SERVICE.LOG_ENTRY_ID = LGP.LOG_ENTRY_ID
        AND LGP_SERVICE.NAME           = 'simcard'
        AND ROWNUM                     < 2
        ) AS SIMCARD,
        (SELECT LGP_SERVICE.VALUE
        FROM VFE_LOG.LG_ENTRY_PARAMETERS LGP_SERVICE
        WHERE LGP_SERVICE.LOG_ENTRY_ID = LGP.LOG_ENTRY_ID
        AND LGP_SERVICE.NAME           = 'account'
        AND ROWNUM                     < 2
        ) AS ACCOUNT,
        (SELECT LGP_SERVICE.VALUE
        FROM VFE_LOG.LG_ENTRY_PARAMETERS LGP_SERVICE
        WHERE LGP_SERVICE.LOG_ENTRY_ID = LGP.LOG_ENTRY_ID
        AND LGP_SERVICE.NAME           = 'customer'
        AND ROWNUM                     < 2
        ) AS CUSTOMER,
        (SELECT LGP_SERVICE.VALUE
        FROM VFE_LOG.LG_ENTRY_PARAMETERS LGP_SERVICE
        WHERE LGP_SERVICE.LOG_ENTRY_ID = LGP.LOG_ENTRY_ID
        AND LGP_SERVICE.NAME           = 'signalmax'
        AND ROWNUM                     < 2
        ) AS SIGNALMAX
      FROM VFE_LOG.LG_ENTRY_PARAMETERS LGP
      )
    ) LGP
  ON LG.ID          = LGP.LOG_ENTRY_ID
  WHERE LG.LOG_TYPE = 4
  ORDER BY TIMESTAMP DESC;
  --------------------------------------------------------
  --  DDL for Index CFG_PROFILES_INDEX1
  --------------------------------------------------------
  CREATE INDEX "CFG_PROFILES_INDEX1" ON "CFG_PROFILES"
    (
      "NAME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_LOGENTRIES_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "LG_LOGENTRIES_PK" ON "LG_LOGENTRIES"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_PROCESSES_UK1
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_PROCESSES_UK1" ON "CFG_PROCESSES"
  (
    "DESCRIPTION"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_PROCESSES_INDEX1
  --------------------------------------------------------
  CREATE INDEX "CFG_PROCESSES_INDEX1" ON "CFG_PROCESSES"
    (
      "ID",
      "DESCRIPTION"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_USERS_INDEX1
  --------------------------------------------------------
  CREATE INDEX "CFG_USERS_INDEX1" ON "CFG_USERS"
    (
      "NAME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_LOCAL_INDEX1
  --------------------------------------------------------
  CREATE INDEX "CFG_LOCAL_INDEX1" ON "CFG_LOCAL"
    (
      "NAME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_SOAPSERVICES_INDEX1
  --------------------------------------------------------
  CREATE INDEX "CFG_SOAPSERVICES_INDEX1" ON "CFG_SOAPSERVICES"
    (
      "SERVICENAME"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_LOGCRITERIA_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_LOGCRITERIA_PK" ON "CFG_LOGCRITERIA"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_ENTRY_PARAMETERS_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "LG_ENTRY_PARAMETERS_PK" ON "LG_ENTRY_PARAMETERS"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_SOAP_CRITERIA_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_SOAP_CRITERIA_PK" ON "CFG_SOAP_CRITERIA"
  (
    "SOAP_ID", "CRITERIA_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_EVENTS_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_EVENTS_PK" ON "CFG_EVENTS"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_LOCAL_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_LOCAL_PK" ON "CFG_LOCAL"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_SERVICESCRITERIA_UK1
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_SERVICESCRITERIA_UK1" ON "CFG_SERVICESCRITERIA"
  (
    "SERVICEID", "CRITERIAID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_EVENT_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "LG_EVENT_PK" ON "LG_EVENT"
  (
    "LOG_ENTRYID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_EVENTS_U01
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_EVENTS_U01" ON "CFG_EVENTS"
  (
    "EVENT_NAME"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index IDX$$_004A0002
  --------------------------------------------------------
  CREATE INDEX "IDX$$_004A0002" ON "LG_ERRORSLOG"
    (
      "LOGENTRYID"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_USERS_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_USERS_PK" ON "CFG_USERS"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_EVENT_CRITERIA_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_EVENT_CRITERIA_PK" ON "CFG_EVENT_CRITERIA"
  (
    "EVENT_ID", "CRITERIA_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_CUSTOM_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "LG_CUSTOM_PK" ON "LG_CUSTOM"
  (
    "LOGENTRYID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_SUCCESSCRITERIA_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_SUCCESSCRITERIA_PK" ON "CFG_SUCCESSCRITERIA"
  (
    "SERVICEID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_SOAPREQUESTS_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "LG_SOAPREQUESTS_PK" ON "LG_SOAPREQUESTS"
  (
    "LOGENTRYID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_CUSTOM_EVENT_TYPE_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_CUSTOM_EVENT_TYPE_PK" ON "CFG_CUSTOM_EVENT_TYPE"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_EVENT_INDEX1
  --------------------------------------------------------
  CREATE INDEX "LG_EVENT_INDEX1" ON "LG_EVENT"
    (
      "TIMESTAMP"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_PROCESSES_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_PROCESSES_PK" ON "CFG_PROCESSES"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_SOAPSERVICES_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_SOAPSERVICES_PK" ON "CFG_SOAPSERVICES"
  (
    "SERVICEID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_MASKCRITERIA_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_MASKCRITERIA_PK" ON "CFG_MASKCRITERIA"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_LOGENTRIES_INDEX1
  --------------------------------------------------------
  CREATE INDEX "LG_LOGENTRIES_INDEX1" ON "LG_LOGENTRIES"
    (
      "TIMESTAMP"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_SOAPREQUESTS_INDEX1
  --------------------------------------------------------
  CREATE INDEX "LG_SOAPREQUESTS_INDEX1" ON "LG_SOAPREQUESTS"
    (
      "TIMESTAMP"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index LG_ERRORSLOG_INDEX1
  --------------------------------------------------------
  CREATE INDEX "LG_ERRORSLOG_INDEX1" ON "LG_ERRORSLOG"
    (
      "TIMESTAMP"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "UFE_LOGVW";
  --------------------------------------------------------
  --  DDL for Index CFG_PROFILES_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_PROFILES_PK" ON "CFG_PROFILES"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_CRITERIA_PK
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_CRITERIA_PK" ON "CFG_CRITERIA"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  DDL for Index CFG_CUSTOM_EVENT_TYPE_NAME_IDX
  --------------------------------------------------------
CREATE UNIQUE INDEX "CFG_CUSTOM_EVENT_TYPE_NAME_IDX" ON "CFG_CUSTOM_EVENT_TYPE"
  (
    "NAME"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "UFE_LOGVW" ;
  --------------------------------------------------------
  --  Constraints for Table LG_SOAPREQUESTS
  --------------------------------------------------------
  ALTER TABLE "LG_SOAPREQUESTS" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "LG_SOAPREQUESTS" MODIFY ("LOGENTRYID" NOT NULL ENABLE);
  ALTER TABLE "LG_SOAPREQUESTS" ADD CONSTRAINT "LG_SOAPREQUESTS_PK" PRIMARY KEY ("LOGENTRYID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_EVENT_CRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_EVENT_CRITERIA" ADD CONSTRAINT "CFG_EVENT_CRITERIA_PK" PRIMARY KEY ("EVENT_ID", "CRITERIA_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_USERS
  --------------------------------------------------------
  ALTER TABLE "CFG_USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_USERS" ADD CONSTRAINT "CFG_USERS_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_LOCAL
  --------------------------------------------------------
  ALTER TABLE "CFG_LOCAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_LOCAL" ADD CONSTRAINT "CFG_LOCAL_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_SERVICESCRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_SERVICESCRITERIA" ADD CONSTRAINT "CFG_SERVICESCRITERIA_UK1" UNIQUE ("SERVICEID", "CRITERIAID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_PROCESSES
  --------------------------------------------------------
  ALTER TABLE "CFG_PROCESSES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_PROCESSES" ADD CONSTRAINT "CFG_PROCESSES_UK1" UNIQUE ("DESCRIPTION") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  ALTER TABLE "CFG_PROCESSES" ADD CONSTRAINT "CFG_PROCESSES_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_CRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_CRITERIA" ADD CONSTRAINT "CFG_CRITERIA_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  ALTER TABLE "CFG_CRITERIA" MODIFY ("REGEX" NOT NULL ENABLE);
  ALTER TABLE "CFG_CRITERIA" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "CFG_CRITERIA" MODIFY ("NAME" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Constraints for Table CFG_MASKCRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_MASKCRITERIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_MASKCRITERIA" ADD CONSTRAINT "CFG_MASKCRITERIA_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_EVENTS
  --------------------------------------------------------
  ALTER TABLE "CFG_EVENTS" ADD CONSTRAINT "CFG_EVENTS_U01" UNIQUE ("EVENT_NAME") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  ALTER TABLE "CFG_EVENTS" ADD CONSTRAINT "CFG_EVENTS_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  ALTER TABLE "CFG_EVENTS" MODIFY ("LOG_JSON_OUT" NOT NULL ENABLE);
  ALTER TABLE "CFG_EVENTS" MODIFY ("LOG_JSON_IN" NOT NULL ENABLE);
  ALTER TABLE "CFG_EVENTS" MODIFY ("LOG_EVENT" NOT NULL ENABLE);
  ALTER TABLE "CFG_EVENTS" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Constraints for Table LG_LOGENTRIES
  --------------------------------------------------------
  ALTER TABLE "LG_LOGENTRIES" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "LG_LOGENTRIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LG_LOGENTRIES" ADD CONSTRAINT "LG_LOGENTRIES_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_SUCCESSCRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_SUCCESSCRITERIA" MODIFY ("SERVICEID" NOT NULL ENABLE);
  ALTER TABLE "CFG_SUCCESSCRITERIA" ADD CONSTRAINT "CFG_SUCCESSCRITERIA_PK" PRIMARY KEY ("SERVICEID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table LG_ENTRY_PARAMETERS
  --------------------------------------------------------
  ALTER TABLE "LG_ENTRY_PARAMETERS" ADD CONSTRAINT "LG_ENTRY_PARAMETERS_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  ALTER TABLE "LG_ENTRY_PARAMETERS" MODIFY ("LOG_ENTRY_ID" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Constraints for Table CFG_PROFILES
  --------------------------------------------------------
  ALTER TABLE "CFG_PROFILES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_PROFILES" ADD CONSTRAINT "CFG_PROFILES_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table LG_CUSTOM
  --------------------------------------------------------
  ALTER TABLE "LG_CUSTOM" ADD CONSTRAINT "LG_CUSTOM_PK" PRIMARY KEY ("LOGENTRYID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  ALTER TABLE "LG_CUSTOM" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "LG_CUSTOM" MODIFY ("LOGENTRYID" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Constraints for Table CFG_LOGCRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_LOGCRITERIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CFG_LOGCRITERIA" ADD CONSTRAINT "CFG_LOGCRITERIA_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_SOAP_CRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_SOAP_CRITERIA" ADD CONSTRAINT "CFG_SOAP_CRITERIA_PK" PRIMARY KEY ("SOAP_ID", "CRITERIA_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_SOAPSERVICES
  --------------------------------------------------------
  ALTER TABLE "CFG_SOAPSERVICES" MODIFY ("SERVICEID" NOT NULL ENABLE);
  ALTER TABLE "CFG_SOAPSERVICES" ADD CONSTRAINT "CFG_SOAPSERVICES_PK" PRIMARY KEY ("SERVICEID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table LG_EVENT
  --------------------------------------------------------
  ALTER TABLE "LG_EVENT" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "LG_EVENT" MODIFY ("LOG_ENTRYID" NOT NULL ENABLE);
  ALTER TABLE "LG_EVENT" ADD CONSTRAINT "LG_EVENT_PK" PRIMARY KEY ("LOG_ENTRYID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  --------------------------------------------------------
  --  Constraints for Table CFG_CUSTOM_EVENT_TYPE
  --------------------------------------------------------
  ALTER TABLE "CFG_CUSTOM_EVENT_TYPE" ADD CONSTRAINT "CFG_CFG_CUSTOM_EVENT_TYPE_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "UFE_LOGVW" ENABLE;
  ALTER TABLE "CFG_CUSTOM_EVENT_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CFG_CUSTOM_EVENT_TYPE" MODIFY ("ID" NOT NULL ENABLE);
  --------------------------------------------------------
  --  Ref Constraints for Table CFG_EVENT_CRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_EVENT_CRITERIA" ADD CONSTRAINT "CFG_EVENT_CRITERIA_R01" FOREIGN KEY ("EVENT_ID") REFERENCES "CFG_EVENTS" ("ID") ENABLE;
  ALTER TABLE "CFG_EVENT_CRITERIA" ADD CONSTRAINT "CFG_EVENT_CRITERIA_R02" FOREIGN KEY ("CRITERIA_ID") REFERENCES "CFG_CRITERIA" ("ID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table CFG_MASKCRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_MASKCRITERIA" ADD CONSTRAINT "CFG_MASKCRITERIA_CFG_SOAP_FK1" FOREIGN KEY ("SERVICEID") REFERENCES "CFG_SOAPSERVICES" ("SERVICEID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table CFG_SOAP_CRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_SOAP_CRITERIA" ADD CONSTRAINT "CFG_SOAP_CRITERIA_R01" FOREIGN KEY ("SOAP_ID") REFERENCES "CFG_SOAPSERVICES" ("SERVICEID") ENABLE;
  ALTER TABLE "CFG_SOAP_CRITERIA" ADD CONSTRAINT "CFG_SOAP_CRITERIA_R02" FOREIGN KEY ("CRITERIA_ID") REFERENCES "CFG_CRITERIA" ("ID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table CFG_SUCCESSCRITERIA
  --------------------------------------------------------
  ALTER TABLE "CFG_SUCCESSCRITERIA" ADD CONSTRAINT "CFG_SUCCESSCRITERIA_CFG_S_FK1" FOREIGN KEY ("SERVICEID") REFERENCES "CFG_SOAPSERVICES" ("SERVICEID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table LG_CUSTOM
  --------------------------------------------------------
  ALTER TABLE "LG_CUSTOM" ADD CONSTRAINT "LG_CUSTOM_R01" FOREIGN KEY ("EVENT_TYPE") REFERENCES "CFG_CUSTOM_EVENT_TYPE" ("ID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table LG_ENTRY_PARAMETERS
  --------------------------------------------------------
  ALTER TABLE "LG_ENTRY_PARAMETERS" ADD CONSTRAINT "LG_ENTRY_PARAMETERS_R01" FOREIGN KEY ("LOG_ENTRY_ID") REFERENCES "LG_LOGENTRIES" ("ID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table LG_ERRORSLOG
  --------------------------------------------------------
  ALTER TABLE "LG_ERRORSLOG" ADD CONSTRAINT "LG_ERRORSLOG_LG_LOGENTRIE_FK1" FOREIGN KEY ("LOGENTRYID") REFERENCES "LG_LOGENTRIES" ("ID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table LG_EVENT
  --------------------------------------------------------
  ALTER TABLE "LG_EVENT" ADD CONSTRAINT "LG_EVENT_LG_LOGENTRIES_FK1" FOREIGN KEY ("LOG_ENTRYID") REFERENCES "LG_LOGENTRIES" ("ID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table LG_LOGENTRIES
  --------------------------------------------------------
  ALTER TABLE "LG_LOGENTRIES" ADD CONSTRAINT "LG_LOGENTRIES_CFG_LOCAL_FK1" FOREIGN KEY ("LOCALID") REFERENCES "CFG_LOCAL" ("ID") ENABLE;
  ALTER TABLE "LG_LOGENTRIES" ADD CONSTRAINT "LG_LOGENTRIES_CFG_PROCESS_FK1" FOREIGN KEY ("PROCESSID") REFERENCES "CFG_PROCESSES" ("ID") ENABLE;
  ALTER TABLE "LG_LOGENTRIES" ADD CONSTRAINT "LG_LOGENTRIES_CFG_PROFILE_FK1" FOREIGN KEY ("PROFILEID") REFERENCES "CFG_PROFILES" ("ID") ENABLE;
  ALTER TABLE "LG_LOGENTRIES" ADD CONSTRAINT "LG_LOGENTRIES_CFG_USERS_FK1" FOREIGN KEY ("USERID") REFERENCES "CFG_USERS" ("ID") ENABLE;
  --------------------------------------------------------
  --  Ref Constraints for Table LG_SOAPREQUESTS
  --------------------------------------------------------
  ALTER TABLE "LG_SOAPREQUESTS" ADD CONSTRAINT "LG_SOAPREQUESTS_CFG_SOAPS_FK1" FOREIGN KEY ("SERVICEID") REFERENCES "CFG_SOAPSERVICES" ("SERVICEID") ENABLE;
  ALTER TABLE "LG_SOAPREQUESTS" ADD CONSTRAINT "LG_SOAPREQUESTS_LG_LOGENT_FK1" FOREIGN KEY ("LOGENTRYID") REFERENCES "LG_LOGENTRIES" ("ID") ENABLE;
