SET DEFINE OFF;
ALTER SESSION SET CURRENT_SCHEMA = UNIFIED_USE;

-- Add user management route

INSERT INTO REFDATAITEM 
(REFDATAITEM_ID, EXPORTABLE, NAME, TIME, TYPE, VALUE, VERSION)
VALUES ((SELECT COALESCE(MAX (REFDATAITEM_ID) + 1, 1) FROM REFDATAITEM),
 1,  'action.java.uam.user', sysdate, 'JSON', 
'{
    "className": "com.celfocus.use.uam.services.UserManagement",
    "application": "login"
}', 1);

INSERT INTO ROUTE 
(ID, NAME, MATCHING_SCRIPT, ACTION_CONFIGURATION, IS_PUBLIC, ORCH_EVAL,
CREATION_DATE, CREATION_USER, LAST_UPDATE_DATE, LAST_UPDATE_USER)
VALUES (COALESCE((SELECT MAX (ID) + 1 FROM ROUTE), 1),
'usermanagementservices', 'targetIs("/services/uam/user")',
'["java.uam.user"]', 1,
NULL, SYSDATE, 'DFC', SYSDATE, 'DFC');

-- Add role management services

INSERT INTO REFDATAITEM 
(REFDATAITEM_ID, EXPORTABLE, NAME, TIME, TYPE, VALUE, VERSION)
VALUES ((SELECT MAX(REFDATAITEM_ID) + 1 FROM REFDATAITEM),
 1, 'action.java.uam.role', sysdate, 'JSON',
 '{
    "className": "com.celfocus.use.uam.services.RoleManagement",
    "application": "login"
}', 1);

INSERT INTO ROUTE
(ID, NAME, MATCHING_SCRIPT, ACTION_CONFIGURATION, IS_PUBLIC, ORCH_EVAL,
CREATION_DATE, CREATION_USER, LAST_UPDATE_DATE, LAST_UPDATE_USER)
VALUES ((SELECT MAX(ID) + 1 FROM ROUTE),
'rolemanagementservices', 'targetIs("/services/uam/role")',
'["java.uam.role"]', 1,
NULL, SYSDATE, 'DFC', SYSDATE, 'DFC');

-- Add asset management services

INSERT INTO REFDATAITEM 
(REFDATAITEM_ID, EXPORTABLE, NAME, TIME, TYPE, VALUE, VERSION)
VALUES ((SELECT MAX(REFDATAITEM_ID) + 1 FROM REFDATAITEM),
 1, 'action.java.uam.asset', sysdate, 'JSON', '{
    "className": "com.celfocus.use.uam.services.AssetManagement",
    "application": "login"
}', 1);

INSERT INTO ROUTE
(ID, NAME, MATCHING_SCRIPT, ACTION_CONFIGURATION, IS_PUBLIC, ORCH_EVAL,
CREATION_DATE, CREATION_USER, LAST_UPDATE_DATE, LAST_UPDATE_USER)
VALUES ((SELECT MAX(ID) + 1 FROM ROUTE),
'assetmanagementservices', 'targetIs("/services/uam/asset")',
'["java.uam.asset"]', 1,
NULL, SYSDATE, 'DFC', SYSDATE, 'DFC');



-- Add process assets

INSERT INTO UAM_ASSET
(ID, TYPE, NAME, DESCRIPTION, ACTIVE, 
CREATION_USER, CREATION_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE)
VALUES (COALESCE((SELECT MAX(ID) + 1 FROM UAM_ASSET), 1),
'UserManagement', 'RW_ASSET', 'Can create/edit/delete assets', '1',
'DFC', sysdate, 'DFC', sysdate);

INSERT INTO UAM_ASSET
(ID, TYPE, NAME, DESCRIPTION, ACTIVE, 
CREATION_USER, CREATION_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE)
VALUES ((SELECT MAX(ID) + 1 FROM UAM_ASSET),
'UserManagement', 'RW_ROLE', 'Can create/edit/delete roles', '1',
'DFC', sysdate, 'DFC', sysdate);

INSERT INTO UAM_ASSET
(ID, TYPE, NAME, DESCRIPTION, ACTIVE, 
CREATION_USER, CREATION_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE)
VALUES ((SELECT MAX(ID) + 1 FROM UAM_ASSET),
'UserManagement', 'RW_PROFILE', 'Can create/edit/delete profiles', 
'1', 'DFC', sysdate, 'DFC', sysdate);

INSERT INTO UAM_ASSET
(ID, TYPE, NAME, DESCRIPTION, ACTIVE, 
CREATION_USER, CREATION_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE)
VALUES ((SELECT MAX(ID) + 1 FROM UAM_ASSET),
'UserManagement', 'RW_USER', 'Can create/edit/delete users', '1',
'DFC', sysdate, 'DFC', sysdate);
             
INSERT INTO UAM_ROLE 
(ID, TYPE, NAME, DESCRIPTION, ACTIVE, 
CREATION_USER, CREATION_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE)
VALUES (COALESCE((SELECT MAX(ID) + 1 FROM UAM_ROLE), 1),
'UserManagement', 'User Access Manager', 
'Can manage users and their access permissions.', '1',
'DFC', sysdate, 'DFC', sysdate);

INSERT INTO UAM_ROLE_ASSETS
(ROLE_ID, ASSET_ID, USER_EXPRESSION, TARGET_EXPRESSION, ACTIVE,
CREATION_USER, CREATION_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE)
VALUES ((SELECT ID FROM UAM_ROLE WHERE NAME = 'User Access Manager'),
(SELECT ID FROM UAM_ASSET WHERE NAME = 'RW_ASSET'), 
NULL, NULL, 1, 'DFC', SYSDATE, 'DFC', SYSDATE);

INSERT INTO UAM_ROLE_ASSETS
(ROLE_ID, ASSET_ID, USER_EXPRESSION, TARGET_EXPRESSION, ACTIVE,
CREATION_USER, CREATION_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE)
VALUES ((SELECT ID FROM UAM_ROLE WHERE NAME = 'User Access Manager'),
(SELECT ID FROM UAM_ASSET WHERE NAME = 'RW_ROLE'),
NULL, NULL, 1, 'DFC', SYSDATE, 'DFC', SYSDATE);

INSERT INTO UAM_ROLE_ASSETS
(ROLE_ID, ASSET_ID, USER_EXPRESSION, TARGET_EXPRESSION, ACTIVE,
CREATION_USER, CREATION_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE)
VALUES ((SELECT ID FROM UAM_ROLE WHERE NAME = 'User Access Manager'),
(SELECT ID FROM UAM_ASSET WHERE NAME = 'RW_USER'),
NULL, NULL, 1, 'DFC', SYSDATE, 'DFC', SYSDATE);
             
COMMIT;